In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('battery_features1.csv')

In [3]:
df

,cycle,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,charge_max,charge_min,time_max,time_min,capacity
0,cyc0000,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,744.988190,-739.819699,735956.805853,735954.817226,1484.807889
1,cyc0000,2,3.780752,0.235468,4.199935,2.699652,40.063822,41.233673,743.231169,-734.818966,735956.798417,735954.815839,1478.050135
2,cyc0000,3,3.779498,0.236901,4.199993,2.699893,40.056912,40.821388,742.190931,-735.119595,735956.806229,735954.817023,1477.310526
3,cyc0000,4,3.781270,0.235397,4.199971,2.699957,40.411244,41.717407,743.483060,-735.978343,735956.802934,735954.816373,1479.461402
4,cyc0000,5,3.779743,0.236809,4.200020,2.699810,41.040121,42.279404,743.402562,-735.336071,735956.797158,735954.816032,1478.738633
...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,cyc8000,1,3.810296,0.225690,4.199990,2.699952,40.356160,41.486858,573.921485,-571.295434,736579.925085,736578.297026,1145.216919
362,cyc8000,3,3.809801,0.224835,4.199879,2.699899,40.392256,41.245789,580.146677,-577.018741,736588.263193,736586.621994,1157.165418
363,cyc8100,1,3.813243,0.222302,4.200110,2.700073,40.397670,41.611675,573.380027,-570.271151,736588.249150,736586.622190,1143.651178
364,cyc8100,3,3.807788,0.227467,4.199999,2.699979,40.353739,41.133438,578.226266,-575.385072,736595.073157,736593.436188,1153.611338
365,cyc8200,1,3.810757,0.225464,4.199910,2.699992,40.329775,41.449417,571.638740,-568.855208,736595.051220,736593.428085,1140.493948

In [4]:
df['cell_id'].value_counts().index

Index([1, 3, 2, 4, 5, 6], dtype='int64', name='cell_id')

In [5]:

df1 = df.sort_values(by=['cell_id'],)
df2 = df1.set_index('cycle')
df2.sort_values(by = ['cell_id', 'cycle'])

,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,charge_max,charge_min,time_max,time_min,capacity
cycle,,,,,,,,,,,,
cyc0000,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,744.988190,-739.819699,735956.805853,735954.817226,1484.807889
cyc0100,1,3.781105,0.236415,4.200017,2.699859,39.937610,41.124866,739.178962,-734.758981,735963.959773,735961.983223,1473.937943
cyc0200,1,3.781842,0.236048,4.199897,2.700020,39.968553,41.243099,734.620310,-731.319321,735971.105070,735969.137114,1465.939631
cyc0300,1,3.782629,0.235614,4.199881,2.699964,39.932417,41.124866,730.326522,-726.827169,735979.750640,735977.791461,1457.153691
cyc0400,1,3.783454,0.235083,4.199881,2.700044,39.959566,41.124866,726.269250,-723.937605,735986.878372,735984.927672,1450.206854
...,...,...,...,...,...,...,...,...,...,...,...,...
cyc4400,6,3.806124,0.222175,4.199821,2.700028,41.062362,42.464920,613.309467,-611.349078,736295.272427,736293.560968,1224.658545
cyc4500,6,3.807284,0.220852,4.199901,2.699948,41.063576,42.577271,611.014624,-608.600935,736303.227379,736301.521307,1219.615560
cyc4600,6,3.805719,0.222110,4.200061,2.699948,41.069193,42.539795,608.987729,-597.292607,736310.158165,736308.467614,1206.280337
cyc4800,6,3.807589,0.222371,4.199961,2.699807,41.076403,42.539795,605.442628,-603.410225,736326.213808,736324.519574,1208.852854
cyc5000,6,3.806696,0.222076,4.200053,2.700019,41.092194,42.527328,589.280011,-586.972989,736350.370700,736348.710235,1176.253001

In [6]:
df.iloc[53]

cycle                     cyc0800
cell_id                         6
voltage_mean             3.787071
voltage_std              0.232765
voltage_max              4.199791
voltage_min              2.699878
temperature_mean        40.913222
temperature_max         42.352524
charge_max             706.592518
charge_min            -704.219359
time_max            736015.810347
time_min            736013.898176
capacity              1410.811877
Name: 53, dtype: object

In [7]:
df1['cell_id'].value_counts().index

Index([1, 3, 2, 4, 5, 6], dtype='int64', name='cell_id')

In [8]:
cap_fade = []
for j in range(df2.shape[0]):
    if j == 0:
        cap_fade.append([0])
    elif df2['cell_id'].iloc[j] == df2['cell_id'].iloc[j-1] and j <=(df2.shape[0]-2):
        cap_fade.append(df2.iloc[j+1,-1] - df2.iloc[j,-1])
    else:
        cap_fade.append(df2.iloc[j,-1] - df2.iloc[j-1,-1])

cap_fade

[[0],
 np.float64(3.1572297353309295),
 np.float64(1.5657412198625025),
 np.float64(328.72102369491813),
 np.float64(-326.4765504704533),
 np.float64(282.67508813053564),
 np.float64(-6.268932867698368),
 np.float64(-19.458392456352158),
 np.float64(12.886763746427732),
 np.float64(-6.431666743412279),
 np.float64(-224.97862690677994),
 np.float64(5.174211195785119),
 np.float64(1.9036389321927345),
 np.float64(2.1912735365040135),
 np.float64(2.2139590601723285),
 np.float64(-8.682972254613333),
 np.float64(-5.03122311451466),
 np.float64(17.03253245350652),
 np.float64(2.8879674695022004),
 np.float64(194.82774257819892),
 np.float64(-35.68929936452105),
 np.float64(24.13585201505066),
 np.float64(5.614745962155894),
 np.float64(-168.8532134934494),
 np.float64(-2.606509549157863),
 np.float64(-7.208743926682018),
 np.float64(2.630228522079733),
 np.float64(-41.73273715483106),
 np.float64(56.664610988319055),
 np.float64(-53.433465194063956),
 np.float64(2.7592471803586704),
 np.float64(194.24521379967064),
 np.float64(-164.1022284805656),
 np.float64(-4.543377876436125),
 np.float64(89.26213957599248),
 np.float64(28.164720130438127),
 np.float64(-5.72942058064109),
 np.float64(-43.8285763959791),
 np.float64(16.595266572481023),
 np.float64(175.19242356766767),
 np.float64(-8.785940852691965),
 np.float64(-13.77059734700265),
 np.float64(6.823761206976087),
 np.float64(-141.02694409716423),
 np.float64(-6.295205590474552),
 np.float64(10.771459004735561),
 np.float64(-39.89500490478167),
 np.float64(65.73857221096614),
 np.float64(-5.3255460314831),
 np.float64(-69.27226015850692),
 np.float64(63.72571095201283),
 np.float64(-69.76268075068015),
 np.float64(-4.367940678831701),
 np.float64(7.075669562011626),
 np.float64(3.1088265862526896),
 np.float64(-24.413396273752596),
 np.float64(-2.4918803257542095),
 np.float64(108.10217991941863),
 np.float64(5.272558202683058),
 np.float64(-103.82293362336213),
 np.float64(-3.182954225574349),
 np.float64(6.849878477464927),
 np.float64(105.68970719335766),
 np.float64(-57.18494031948103),
 np.float64(-12.61430894551495),
 np.float64(-128.5520528488512),
 np.float64(2.0517933602723133),
 np.float64(-4.576697908337337),
 np.float64(-2.2719123740498617),
 np.float64(-3.3694190487453852),
 np.float64(1.572844918486453),
 np.float64(14.541359593094057),
 np.float64(-3.371152215172742),
 np.float64(7.938703415854661),
 np.float64(265.8523580666292),
 np.float64(-268.0859878157171),
 np.float64(-2.333921451594051),
 np.float64(205.73127693733068),
 np.float64(205.73127693733068),
 np.float64(-209.7669406085722),
 np.float64(3.5919504242640414),
 np.float64(223.1514764300939),
 np.float64(10.93527338576473),
 np.float64(-219.39761346593264),
 np.float64(185.90561231021616),
 np.float64(11.305222559098638),
 np.float64(-190.70037999409828),
 np.float64(19.20100896337067),
 np.float64(-59.9698805556427),
 np.float64(-1.1217967777874946),
 np.float64(-4.058002296573477),
 np.float64(51.94611583699566),
 np.float64(-8.570608618773576),
 np.float64(-9.15155657934497),
 np.float64(-24.99066780557405),
 np.float64(85.51590522761853),
 np.float64(3.412870120692787),
 np.float64(4.198893917216083),
 np.float64(-0.47542818719307434),
 np.float64(77.459762399483),
 np.float64(5.8341288755771075),
 np.float64(-10.830684414627967),
 np.float64(-5.538002181606544),
 np.float64(-89.63887972086059),
 np.float64(3.393698852187981),
 np.float64(120.09366248213769),
 np.float64(-116.37759312056642),
 np.float64(-14.36418379226484),
 np.float64(3.1231972157122527),
 np.float64(121.9190162296727),
 np.float64(-68.69237905012528),
 np.float64(36.01117271229418),
 np.float64(-52.789435048762016),
 np.float64(12.760388638462928),
 np.float64(-13.45660772279166),
 np.float64(209.43922888298925),
 np.float64(-66.92540951402202),
 np.float64(11.336826998230435),
 np.float64(-22.2824333831295),
 np.float64(-227.57293344046093),
 np.float64(3.593298087621406),
 np.float64(13.563471232987695),
 np.float64(-3.100310505516063),
 np.float64(-17.563520974308403),
 np.float64(40.883325724506676),
 np.float64(-1.8022312599719044),
 np.float64(140.03533073591916),
 np.float64(86.22421270534687),
 np.float64(6.892744842400134),
 np.float64(16.081555967041368),
 np.float64(-9.016363654736097),
 np.float64(-135.96625255204185),
 np.float64(-4.918979773740375),
 np.float64(-7.456457730207603),
 np.float64(165.66426008487133),
 np.float64(-149.61062525413126),
 np.float64(-24.63629400553691),
 np.float64(-43.78245562674874),
 np.float64(48.46280749824837),
 np.float64(-148.42175617606836),
 np.float64(3.3773258573105522),
 np.float64(277.10880204641285),
 np.float64(-273.45681968416216),
 np.float64(-14.74742660182119),
 np.float64(0.9742741257100533),
 np.float64(1.554765157203292),
 np.float64(-2.7113685903509577),
 np.float64(6.08131411164527),
 np.float64(7.776630032616595),
 np.float64(-14.365681937125373),
 np.float64(24.9514859141575),
 np.float64(24.9514859141575),
 np.float64(-2.739903781975272),
 np.float64(11.308345440117364),
 np.float64(-2.3530537949061454),
 np.float64(-2.416184018003605),
 np.float64(11.15011069810339),
 np.float64(-1.887072410159135),
 np.float64(-2.2462017255577393),
 np.float64(8.394072312026765),
 np.float64(-2.177883086208567),
 np.float64(259.6854732776826),
 np.float64(-6.1386171631040725),
 np.float64(33.902582821006035),
 np.float64(-7.70502188221235),
 np.float64(-14.229808995743724),
 np.float64(6.099857825764275),
 np.float64(-119.48476032819508),
 np.float64(5.7496667892251025),
 np.float64(-50.93872744536816),
 np.float64(36.47237163043815),
 np.float64(-6.129439160887841),
 np.float64(11.108914432088113),
 np.float64(-40.547895146355586),
 np.float64(-12.042689267157584),
 np.float64(3.4526652943225145),
 np.float64(-0.20234784881313317),
 np.float64(-10.724000470882402),
 np.float64(4.077118384849655),
 np.float64(41.456691638251414),
 np.float64(-9.878800646498348),
 np.float64(5.554267483002377),
 np.float64(37.90754851281213),
 np.float64(-4.883230405351696),
 np.float64(9.419403057273485),
 np.float64(5.828314592108654),
 np.float64(-99.4290804735922),
 np.float64(-8.259317686876102),
 np.float64(112.54132754783177),
 np.float64(5.490449547267417),
 np.float64(-114.38990766186998),
 np.float64(-53.17447345337496),
 np.float64(3.4576252787924204),
 np.float64(-11.375359645977369),
 np.float64(2.4063979953587022),
 np.float64(2.5253369406937054),
 np.float64(-12.489306917935664),
 np.float64(1.6901995335776974),
 np.float64(23.36417767885746),
 np.float64(-2.910614558875295),
 np.float64(202.11926880256715),
 np.float64(-195.93579118075627),
 np.float64(11.648819976835512),
 np.float64(9.776451587531483),
 np.float64(8.824025694869079),
 np.float64(-11.545717149478833),
 np.float64(-42.70406124726014),
 np.float64(210.38993333300164),
 np.float64(4.788079923629994),
 np.float64(-9.78255517294815),
 np.float64(-10.588322486789366),
 np.float64(-10.801033087162523),
 np.float64(-108.50234937205505),
 np.float64(-3.074670359517313),
 np.float64(156.83458496292587),
 np.float64(-4.8005833699162395),
 np.float64(9.704046383387777),
 np.float64(4.889646127493734),
 np.float64(-274.69464397449906),
 np.float64(64.82732880804951),
 np.float64(-2.3074077139094697),
 np.float64(11.627371688127141),
 np.float64(-5.779548559731438),
 np.float64(255.33144381545526),
 np.float64(-320.14510758835513),
 np.float64(0.6852235249630212),
 np.float64(243.8667175603241),
 np.float64(243.8667175603241),
 np.float64(-21.256240475662025),
 np.float64(104.6044817915465),
 np.float64(-206.71975067052267),
 np.float64(176.4659112502793),
 np.float64(-30.488041468684514),
 np.float64(15.061855826129886),
 np.float64(8.005439192033464),
 np.float64(-38.99741710888998),
 np.float64(-137.4119657471481),
 np.float64(192.43296376779358),
 np.float64(7.222389066795131),
 np.float64(-211.45288163088412),
 np.float64(1.7524006654066397),
 np.float64(-4.560561435787804),
 np.float64(25.853406547780196),
 np.float64(209.42073747951736),
 np.float64(7.170925791426953),
 np.float64(56.808472764745375),
 np.float64(-180.64644049018443),
 np.float64(-88.45392166642296),
 np.float64(50.848074932414875),
 np.float64(-29.93103608816773),
 np.float64(-15.999314809900625),
 np.float64(40.97891729443336),
 np.float64(-33.7146009906412),
 np.float64(225.45442236924873),
 np.float64(-165.85109985007352),
 np.float64(-5.312967896265718),
 np.float64(154.27783699115457),
 np.float64(-239.79915444552216),
 np.float64(126.39519105761428),
 np.float64(-6.410765107163115),
 np.float64(-112.26765340192173),
 np.float64(19.116779529869973),
 np.float64(48.287516953604836),
 np.float64(22.960019787740976),
 np.float64(-37.736654726827965),
 np.float64(-18.679477106316426),
 np.float64(39.361880973488724),
 np.float64(-50.43917470802512),
 np.float64(25.058834728941292),
 np.float64(47.535851377803056),
 np.float64(163.85511380070625),
 np.float64(10.076125365779262),
 np.float64(-29.103726726443256),
 np.float64(-146.77575575354467),
 np.float64(-146.77575575354467),
 np.float64(-6.818156683820462),
 np.float64(97.68420396869578),
 np.float64(-111.48178596852381),
 np.float64(175.1813567014051),
 np.float64(63.751634577315144),
 np.float64(-69.61735041933116),
 np.float64(17.436217677979585),
 np.float64(-359.56573680270503),
 np.float64(353.6701709564363),
 np.float64(-136.32596708358915),
 np.float64(181.39401219269575),
 np.float64(-32.74423002122853),
 np.float64(6.922632815496627),
 np.float64(-151.84705485618633),
 np.float64(-18.512493385186644),
 np.float64(39.96840934539023),
 np.float64(147.5903175126491),
 np.float64(-9.59790948109503),
 np.float64(-133.75324600362705),
 np.float64(-77.40485767405312),
 np.float64(109.03572033188311),
 np.float64(-14.99009505696722),
 np.float64(4.674929150971366),
 np.float64(-101.46003048122657),
 np.float64(163.91629895141978),
 np.float64(-170.9056612286481),
 np.float64(176.93085759355722),
 np.float64(-160.20089526884794),
 np.float64(113.8524735499268),
 np.float64(-107.59932094870283),
 np.float64(-3.2101387458862973),
 np.float64(140.05471436438165),
 np.float64(-46.29297736384069),
 np.float64(-82.74780916102418),
 np.float64(12.721526707755856),
 np.float64(29.604234885493042),
 np.float64(5.6736227172164035),
 np.float64(18.803823358968657),
 np.float64(-63.42362214260038),
 np.float64(35.9106486369069),
 np.float64(22.957659790750768),
 np.float64(49.71205643336202),
 np.float64(22.645210644034023),
 np.float64(-10.832706947971019),
 np.float64(-141.81923287138352),
 np.float64(-141.81923287138352),
 np.float64(8.32541999778823),
 np.float64(-41.91916145053847),
 np.float64(38.39991324918333),
 np.float64(40.41747282324263),
 np.float64(11.747418309132172),
 np.float64(-34.652788989673354),
 np.float64(6.098703844476404),
 np.float64(-9.529080777763056),
 np.float64(164.82325424414853),
 np.float64(-33.49132872237578),
 np.float64(16.062207741680595),
 np.float64(-8.294823539527215),
 np.float64(17.934792530561026),
 np.float64(-142.7030812483497),
 np.float64(-56.87088175961321),
 np.float64(18.40189021423862),
 np.float64(19.645070302168733),
 np.float64(-24.249508670785417),
 np.float64(-27.364532381944173),
 np.float64(4.628115084616184),
 np.float64(8.353598824061919),
 np.float64(-32.27474473225129),
 np.float64(-18.378208300955976),
 np.float64(138.68259485207477),
 np.float64(-125.34737209732725),
 np.float64(112.73219785083575),
 np.float64(-11.250281413295397),
 np.float64(-144.84447532011063),
 np.float64(58.635706351953104),
 np.float64(116.14977706345326),
 np.float64(10.594786679772369),
 np.float64(-130.46620947157817),
 np.float64(155.22628381947743),
 np.float64(-11.849541390756485),
 np.float64(5.705919928674348),
 np.float64(12.199491793674952),
 np.float64(-164.56068908665043),
 np.float64(170.7628643282021),
 np.float64(-189.79853702512355),
 np.float64(196.19312257090337),
 np.float64(12.956369412151844),
 np.float64(6.567660253981103),
 np.float64(-13.758128409298706),
 np.float64(64.90073026492132),
 np.float64(64.90073026492132)]

In [9]:
df2.index

Index(['cyc0000', 'cyc8200', 'cyc8100', 'cyc8000', 'cyc0100', 'cyc7900',
       'cyc0700', 'cyc0800', 'cyc1100', 'cyc0900',
       ...
       'cyc1300', 'cyc1100', 'cyc4300', 'cyc1000', 'cyc4800', 'cyc0900',
       'cyc0700', 'cyc0600', 'cyc0800', 'cyc0000'],
      dtype='object', name='cycle', length=366)

In [10]:
df = df.sort_values(['cell_id','cycle'])

df['capacity_fade'] = df.groupby('cell_id')['capacity'].diff()

df['capacity_fade'] = df['capacity_fade'].fillna(0)

df[['cell_id','cycle','capacity','capacity_fade']].head(20)

     cell_id    cycle     capacity  capacity_fade
0          1  cyc0000  1484.807889       0.000000
6          1  cyc0100  1473.937943     -10.869946
12         1  cyc0200  1465.939631      -7.998311
18         1  cyc0300  1457.153691      -8.785941
24         1  cyc0400  1450.206854      -6.946836
30         1  cyc0500  1443.383093      -6.823761
36         1  cyc0600  1436.701246      -6.681848
42         1  cyc0700  1430.136481      -6.564765
48         1  cyc0800  1423.867548      -6.268933
54         1  cyc0900  1417.295919      -6.571629
60         1  cyc1000  1410.864252      -6.431667
66         1  cyc1100  1404.409155      -6.455097
72         1  cyc1200  1398.402755      -6.006400
78         1  cyc1300  1392.464054      -5.938701
84         1  cyc1400  1386.849308      -5.614746
90         1  cyc1600  1374.928685     -11.920623
96         1  cyc1800  1362.713456     -12.215229
102        1  cyc1900  1356.684670      -6.028786
108        1  cyc2000  1351.150972      -5.533698
114        1  cyc2100  1345.878414      -5.272558

In [11]:
df = df.drop(columns = ['charge_max', 'charge_min', 'time_max', 'time_min'])

In [12]:
df

,cycle,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,capacity,capacity_fade
0,cyc0000,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,1484.807889,0.000000
6,cyc0100,1,3.781105,0.236415,4.200017,2.699859,39.937610,41.124866,1473.937943,-10.869946
12,cyc0200,1,3.781842,0.236048,4.199897,2.700020,39.968553,41.243099,1465.939631,-7.998311
18,cyc0300,1,3.782629,0.235614,4.199881,2.699964,39.932417,41.124866,1457.153691,-8.785941
24,cyc0400,1,3.783454,0.235083,4.199881,2.700044,39.959566,41.124866,1450.206854,-6.946836
...,...,...,...,...,...,...,...,...,...,...
250,cyc4400,6,3.806124,0.222175,4.199821,2.700028,41.062362,42.464920,1224.658545,-3.229981
256,cyc4500,6,3.807284,0.220852,4.199901,2.699948,41.063576,42.577271,1219.615560,-5.042986
262,cyc4600,6,3.805719,0.222110,4.200061,2.699948,41.069193,42.539795,1206.280337,-13.335223
268,cyc4800,6,3.807589,0.222371,4.199961,2.699807,41.076403,42.539795,1208.852854,2.572517
274,cyc5000,6,3.806696,0.222076,4.200053,2.700019,41.092194,42.527328,1176.253001,-32.599853

In [13]:

df['cycle_number'] = df['cycle'].str.extract(r'(\d+)').astype(int) // 100


df = df.sort_values(['cell_id','cycle_number']).reset_index(drop=True)

In [14]:
df

,cycle,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,capacity,capacity_fade,cycle_number
0,cyc0000,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,1484.807889,0.000000,0
1,cyc0100,1,3.781105,0.236415,4.200017,2.699859,39.937610,41.124866,1473.937943,-10.869946,1
2,cyc0200,1,3.781842,0.236048,4.199897,2.700020,39.968553,41.243099,1465.939631,-7.998311,2
3,cyc0300,1,3.782629,0.235614,4.199881,2.699964,39.932417,41.124866,1457.153691,-8.785941,3
4,cyc0400,1,3.783454,0.235083,4.199881,2.700044,39.959566,41.124866,1450.206854,-6.946836,4
...,...,...,...,...,...,...,...,...,...,...,...
361,cyc4400,6,3.806124,0.222175,4.199821,2.700028,41.062362,42.464920,1224.658545,-3.229981,44
362,cyc4500,6,3.807284,0.220852,4.199901,2.699948,41.063576,42.577271,1219.615560,-5.042986,45
363,cyc4600,6,3.805719,0.222110,4.200061,2.699948,41.069193,42.539795,1206.280337,-13.335223,46
364,cyc4800,6,3.807589,0.222371,4.199961,2.699807,41.076403,42.539795,1208.852854,2.572517,48
365,cyc5000,6,3.806696,0.222076,4.200053,2.700019,41.092194,42.527328,1176.253001,-32.599853,50

In [15]:

initial_capacity = df.groupby('cell_id')['capacity'].transform('first')


df['SOH'] = df['capacity'] / initial_capacity


df[['cell_id','cycle','capacity','SOH']].head(20)

    cell_id    cycle     capacity       SOH
0         1  cyc0000  1484.807889  1.000000
1         1  cyc0100  1473.937943  0.992679
2         1  cyc0200  1465.939631  0.987292
3         1  cyc0300  1457.153691  0.981375
4         1  cyc0400  1450.206854  0.976697
5         1  cyc0500  1443.383093  0.972101
6         1  cyc0600  1436.701246  0.967601
7         1  cyc0700  1430.136481  0.963179
8         1  cyc0800  1423.867548  0.958957
9         1  cyc0900  1417.295919  0.954532
10        1  cyc1000  1410.864252  0.950200
11        1  cyc1100  1404.409155  0.945852
12        1  cyc1200  1398.402755  0.941807
13        1  cyc1300  1392.464054  0.937808
14        1  cyc1400  1386.849308  0.934026
15        1  cyc1600  1374.928685  0.925998
16        1  cyc1800  1362.713456  0.917771
17        1  cyc1900  1356.684670  0.913711
18        1  cyc2000  1351.150972  0.909984
19        1  cyc2100  1345.878414  0.906433

In [16]:
df = df.drop(columns = ['cycle'])

In [17]:
df

,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,capacity,capacity_fade,cycle_number,SOH
0,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,1484.807889,0.000000,0,1.000000
1,1,3.781105,0.236415,4.200017,2.699859,39.937610,41.124866,1473.937943,-10.869946,1,0.992679
2,1,3.781842,0.236048,4.199897,2.700020,39.968553,41.243099,1465.939631,-7.998311,2,0.987292
3,1,3.782629,0.235614,4.199881,2.699964,39.932417,41.124866,1457.153691,-8.785941,3,0.981375
4,1,3.783454,0.235083,4.199881,2.700044,39.959566,41.124866,1450.206854,-6.946836,4,0.976697
...,...,...,...,...,...,...,...,...,...,...,...
361,6,3.806124,0.222175,4.199821,2.700028,41.062362,42.464920,1224.658545,-3.229981,44,0.829876
362,6,3.807284,0.220852,4.199901,2.699948,41.063576,42.577271,1219.615560,-5.042986,45,0.826459
363,6,3.805719,0.222110,4.200061,2.699948,41.069193,42.539795,1206.280337,-13.335223,46,0.817422
364,6,3.807589,0.222371,4.199961,2.699807,41.076403,42.539795,1208.852854,2.572517,48,0.819165
365,6,3.806696,0.222076,4.200053,2.700019,41.092194,42.527328,1176.253001,-32.599853,50,0.797075

In [18]:
df.columns

Index(['cell_id', 'voltage_mean', 'voltage_std', 'voltage_max', 'voltage_min',
       'temperature_mean', 'temperature_max', 'capacity', 'capacity_fade',
       'cycle_number', 'SOH'],
      dtype='object')

In [19]:
del df1
del df2

In [20]:
import gc
gc.collect()

1781

In [21]:
df

,cell_id,voltage_mean,voltage_std,voltage_max,voltage_min,temperature_mean,temperature_max,capacity,capacity_fade,cycle_number,SOH
0,1,3.780414,0.236429,4.199977,2.699819,39.963427,41.295536,1484.807889,0.000000,0,1.000000
1,1,3.781105,0.236415,4.200017,2.699859,39.937610,41.124866,1473.937943,-10.869946,1,0.992679
2,1,3.781842,0.236048,4.199897,2.700020,39.968553,41.243099,1465.939631,-7.998311,2,0.987292
3,1,3.782629,0.235614,4.199881,2.699964,39.932417,41.124866,1457.153691,-8.785941,3,0.981375
4,1,3.783454,0.235083,4.199881,2.700044,39.959566,41.124866,1450.206854,-6.946836,4,0.976697
...,...,...,...,...,...,...,...,...,...,...,...
361,6,3.806124,0.222175,4.199821,2.700028,41.062362,42.464920,1224.658545,-3.229981,44,0.829876
362,6,3.807284,0.220852,4.199901,2.699948,41.063576,42.577271,1219.615560,-5.042986,45,0.826459
363,6,3.805719,0.222110,4.200061,2.699948,41.069193,42.539795,1206.280337,-13.335223,46,0.817422
364,6,3.807589,0.222371,4.199961,2.699807,41.076403,42.539795,1208.852854,2.572517,48,0.819165
365,6,3.806696,0.222076,4.200053,2.700019,41.092194,42.527328,1176.253001,-32.599853,50,0.797075

In [62]:
df.to_csv('train_final.csv', index = False)