In [1]:
# %%
import scipy.io as sio
import pandas as pd
import numpy as np
import pandas as pd

# Set options to display all rows and columns


data = sio.loadmat('Oxford_Battery_Degradation_Dataset_1.mat')
data.keys()

data['Cell1'][0][0].dtype.names


rows = []
q = []
v = []
t = []
T = []
cell_id = []
phase_name = []
cycle_name = []

for i in range(1,7):
        cell= data['Cell'+str(i)][0][0]
    
    

    
        cycle_names = cell.dtype.names
        
        for cycle in cycle_names:
            cycle_data = cell[cycle][0][0]
            phase_names = cycle_data.dtype.names
            for phase in phase_names:
                phase_data = cycle_data[phase][0][0]
                for j in range(len(phase_data['q'])):
                    q.append(phase_data['q'][j][0])
                    v.append(phase_data['v'][j][0])
                    t.append(phase_data['t'][j][0])
                    T.append(phase_data['T'][j][0])
                    cell_id.append(i)
                    phase_name.append(phase)
                    cycle_name.append(cycle)







    

#print(q)
#print(len(q))
#print(len(v))
#print(len(t))
#print(len(T))
#print(len(cell_id))
#print(len(cycle_name))
#print(len(phase_name))

# %%
df = pd.DataFrame({
    'cell_id': cell_id,
    'cycle': cycle_name,
    'phase': phase_name,
    'charge': q,
    'time': t,
    'temperature': T,
    'voltage': v

}) 
# %%
df.shape
# %%

(10788466, 7)

In [2]:
df.sample(10)

,cell_id,cycle,phase,charge,time,temperature,voltage
8760440,5,cyc2500,OCVch,460.981958,736143.265178,40.920380,3.916379
2243075,1,cyc8000,OCVdc,-294.755244,736579.039722,40.301033,3.797772
8259053,5,cyc0700,OCVch,341.961678,736008.330921,40.907913,3.798356
5381237,3,cyc3200,OCVdc,-557.697968,736201.799113,40.072475,3.580017
5151643,3,cyc2500,OCVch,148.848630,736142.950451,40.072475,3.702816
599628,1,cyc2000,OCVch,646.134177,736106.344599,39.864166,4.148182
8285340,5,cyc0800,OCVch,6.731177,736015.076880,40.907913,3.044306
8466310,5,cyc1300,OCVdc,-499.738686,736050.248026,41.032574,3.706663
8625869,5,cyc2100,C1ch,253.009913,736111.617085,40.446579,3.817475
6912991,4,cyc0800,OCVdc,-489.002547,736014.847602,40.457062,3.720069

In [3]:
df1 = df.copy()

In [4]:
features = df.groupby(["cycle","cell_id"]).agg({
    "voltage": ["mean","std","max","min"],
    "temperature": ["mean","max"],
    "charge": ["max","min"],
    "time": ["max","min"]
})
features.columns = ['_'.join(col) for col in features.columns]
features

                 voltage_mean  voltage_std  voltage_max  voltage_min  \
cycle   cell_id
cyc0000 1            3.780414     0.236429     4.199977     2.699819
        2            3.780752     0.235468     4.199935     2.699652
        3            3.779498     0.236901     4.199993     2.699893
        4            3.781270     0.235397     4.199971     2.699957
        5            3.779743     0.236809     4.200020     2.699810
...                       ...          ...          ...          ...
cyc8000 1            3.810296     0.225690     4.199990     2.699952
        3            3.809801     0.224835     4.199879     2.699899
cyc8100 1            3.813243     0.222302     4.200110     2.700073
        3            3.807788     0.227467     4.199999     2.699979
cyc8200 1            3.810757     0.225464     4.199910     2.699992

                 temperature_mean  temperature_max  charge_max  charge_min  \
cycle   cell_id
cyc0000 1               39.963427        41.295536  744.988190 -739.819699
        2               40.063822        41.233673  743.231169 -734.818966
        3               40.056912        40.821388  742.190931 -735.119595
        4               40.411244        41.717407  743.483060 -735.978343
        5               41.040121        42.279404  743.402562 -735.336071
...                           ...              ...         ...         ...
cyc8000 1               40.356160        41.486858  573.921485 -571.295434
        3               40.392256        41.245789  580.146677 -577.018741
cyc8100 1               40.397670        41.611675  573.380027 -570.271151
        3               40.353739        41.133438  578.226266 -575.385072
cyc8200 1               40.329775        41.449417  571.638740 -568.855208

                      time_max       time_min
cycle   cell_id
cyc0000 1        735956.805853  735954.817226
        2        735956.798417  735954.815839
        3        735956.806229  735954.817023
        4        735956.802934  735954.816373
        5        735956.797158  735954.816032
...                        ...            ...
cyc8000 1        736579.925085  736578.297026
        3        736588.263193  736586.621994
cyc8100 1        736588.249150  736586.622190
        3        736595.073157  736593.436188
cyc8200 1        736595.051220  736593.428085

[366 rows x 10 columns]